services:
  # --- INFRASTRUCTURE ---
  postgres:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: radio_db
    ports: ["5432:5432"]

  redis:
    image: redis:alpine
    restart: always
    ports: ["6379:6379"]

  minio:
    image: minio/minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    volumes:
      - minio_data:/data
    ports: ["9000:9000", "9001:9001"]

  # --- APP ---
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    ports: ["3000:3000"]
    depends_on: [postgres, redis]
    env_file: .env

  worker:
    build:
      context: .
      dockerfile: ./apps/worker/Dockerfile
    depends_on: [postgres, redis, minio]
    env_file: .env

volumes:
  minio_data:
